"""Round-trip reversibility test for the initial-schema migration 5a4ff7266708.

upgrade() creates ~17 tables whose columns declare 19 named Enum types, so
PostgreSQL creates 19 enum types. The autogenerated downgrade() dropped the
tables but NOT the enum types, leaving them orphaned — so `downgrade base` then
`upgrade` failed with `type "..." already exists`.

This can't use the in-transaction monkeypatch trick the other migration tests use:
at head the base tables carry FK dependencies from later migrations, so running
5a4ff's downgrade against the shared DB would fail on those. Instead it runs the
real alembic commands against a throwaway database, scoped to JUST this migration
(`upgrade 5a4ff -> downgrade base -> upgrade 5a4ff`), which both isolates the bug
and is independent of any later migration's state.
"""

import os

from alembic.config import Config
from sqlalchemy import bindparam, create_engine, text
from sqlalchemy.engine import make_url

from alembic import command

_REVISION = "5a4ff7266708"
_ENUM_NAMES = [
    "consideration_type",
    "entity_status",
    "entity_type",
    "extraction_field_type",
    "extraction_status",
    "file_type",
    "finding_severity",
    "finding_status",
    "lead_origin",
    "lead_status",
    "member_role",
    "message_role",
    "note_entity_type",
    "signal_severity",
    "source_type",
    "transaction_type",
    "user_role",
    "workspace_status",
    "workspace_vertical",
]


def _orphan_enum_count(url):
    eng = create_engine(url)
    try:
        with eng.connect() as conn:
            return conn.execute(
                text("SELECT count(*) FROM pg_type WHERE typname IN :names").bindparams(
                    bindparam("names", value=_ENUM_NAMES, expanding=True)
                )
            ).scalar()
    finally:
        eng.dispose()


def test_initial_schema_downgrade_drops_enum_types():
    base = make_url(os.environ["TEST_DATABASE_URL"])
    tmp_db = "catalyst_initschema_rt"
    # Replace only the database name, preserving host/credentials/query options.
    admin_url = base.set(database="postgres")
    tmp_url = base.set(database=tmp_db).render_as_string(hide_password=False)

    admin = create_engine(admin_url, isolation_level="AUTOCOMMIT")
    with admin.connect() as conn:
        conn.execute(text(f"DROP DATABASE IF EXISTS {tmp_db}"))
        conn.execute(text(f"CREATE DATABASE {tmp_db}"))

    saved = os.environ["TEST_DATABASE_URL"]
    try:
        os.environ["TEST_DATABASE_URL"] = tmp_url
        cfg = Config("alembic.ini")

        # Apply only the initial migration → creates tables + 19 enum types.
        command.upgrade(cfg, _REVISION)
        # Roll back to base → must drop the tables AND every enum type.
        command.downgrade(cfg, "base")
        assert _orphan_enum_count(tmp_url) == 0, "initial-schema downgrade orphaned enum types"
        # Re-apply: previously raised `type "..." already exists`.
        command.upgrade(cfg, _REVISION)
    finally:
        os.environ["TEST_DATABASE_URL"] = saved
        with admin.connect() as conn:
            conn.execute(text(f"DROP DATABASE IF EXISTS {tmp_db}"))
        admin.dispose()
