"""phase2f workspace render mode

Revision ID: 50f2b84a06aa
Revises: 45d36706d164
Create Date: 2026-06-01 01:51:23.015003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f2b84a06aa'
down_revision: Union[str, None] = '45d36706d164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_call_log_called_at', table_name='claude_call_logs')
    op.drop_index('idx_call_log_document_id', table_name='claude_call_logs')
    op.alter_column('documents', 'flag_note',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_documents_search_vector', table_name='documents', postgresql_using='gin')
    op.add_column('workspaces', sa.Column('document_render_mode', sa.String(), server_default='schema', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'document_render_mode')
    op.create_index('idx_documents_search_vector', 'documents', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('documents', 'flag_note',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index('idx_call_log_document_id', 'claude_call_logs', ['document_id'], unique=False)
    op.create_index('idx_call_log_called_at', 'claude_call_logs', ['called_at'], unique=False)
    # ### end Alembic commands ###
