"""add schema_change_proposals table and active-schema partial unique index

Revision ID: e1ca59dae292
Revises: f2b3c4d5e6f7
Create Date: 2026-06-23 01:31:49.962595

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e1ca59dae292"
down_revision: str | None = "f2b3c4d5e6f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schema_change_proposals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("workspace_id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(), nullable=True),
        sa.Column("base_schema_id", sa.String(), nullable=True),
        sa.Column(
            "proposal_type",
            sa.Enum("new_schema", "schema_extension", name="proposal_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("draft", "rejected", "applied", "failed", name="proposal_status"),
            nullable=False,
        ),
        sa.Column("proposed_schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("proposed_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("created_by_ai", sa.Boolean(), nullable=False),
        sa.Column("model_id", sa.String(), nullable=True),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("proposer_inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reviewed_by", sa.String(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("apply_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["base_schema_id"],
            ["document_schemas.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_active_schema_type_vertical",
        "document_schemas",
        ["document_type", "vertical"],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_active_schema_type_vertical",
        table_name="document_schemas",
        postgresql_where=sa.text("is_active = true"),
    )
    op.drop_table("schema_change_proposals")
    # ### end Alembic commands ###
    # Alembic's autogenerated downgrade drops the table but NOT the enum types the
    # table's columns created, leaving proposal_type/proposal_status orphaned and
    # breaking a subsequent re-upgrade ("type already exists"). Drop them explicitly.
    op.execute("DROP TYPE IF EXISTS proposal_type")
    op.execute("DROP TYPE IF EXISTS proposal_status")
